### PR TITLE
Add ShareShuffleSketch.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/45)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/45)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @renjiezh)

___
*[`src/main/proto/wfa/any_sketch/share_shuffle_sketch.proto` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/45#-NrbntJ5BglbsDAspxQ5:-NrbntJ5BglbsDAspxQ6:b-ggrkg3) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/2f179ae18ed57035586087e9d3db3fbdabb7cf0d/src/main/proto/wfa/any_sketch/share_shuffle_sketch.proto#L27)):*
> ```proto
> option java_outer_classname = "ShareShuffleSketchProto";
> 
> // The data share of HonestMajorityShareShuffle protocol.
> ```

Deferring to @kungfucraig on whether this naming makes sense.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/45)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/proto/wfa/any_sketch/share_shuffle_sketch.proto` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/45#-NrfL8cl7vfvGLdrfzC4:-NrfL8cl7vfvGLdrfzC5:b-id4bvx) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/2f179ae18ed57035586087e9d3db3fbdabb7cf0d/src/main/proto/wfa/any_sketch/share_shuffle_sketch.proto#L29)):*
> ```proto
> // The data share of HonestMajorityShareShuffle protocol.
> message ShareShuffleSketch {
>   // A vector of counts.
> ```

A vector of count where each count corresponds to the frequency of a single VID.

**Review by ple13 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/45)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @stevenwarejones)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/45)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/45)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/proto/wfa/any_sketch/share_shuffle_sketch.proto` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/45#-Nrk8CPFEXhuaNoDM5ns:-Nrk8CPFEXhuaNoDM5nt:bsng0ct) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/db31899b9a979f389eeb61db1fa26d1f31b3e43f/src/main/proto/wfa/any_sketch/share_shuffle_sketch.proto#L31)):*
> ```proto
>   // A vector of count where each count corresponds to the frequency of a single
>   // VID.
>   repeated uint32 data = 1;
> ```

are we planning to try to compress any of this?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/45)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/any_sketch/share_shuffle_sketch.proto` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/45#-Nrk8CPFEXhuaNoDM5ns:-Nrkgmto9GhrFWtTwGj1:byeivki) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/db31899b9a979f389eeb61db1fa26d1f31b3e43f/src/main/proto/wfa/any_sketch/share_shuffle_sketch.proto#L31)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

are we planning to try to compress any of this?
</blockquote></details>

For now we are not planning to compress the data. But I appreciate this idea and I will keep it in mind.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/45)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
