### PR TITLE
Add the secret share generator function.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @renjiezh and @SanjayVas)

**Review by renjiezh — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37)* status: all files reviewed, 4 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/cc/any_sketch/crypto/secret_share.h` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2SJq5BCCS4R9oB55b:-Nm2SJq5BCCS4R9oB55c:b1qrlj) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/any_sketch/crypto/secret_share.h#L39)):*
> ```objc
>   virtual absl::StatusOr<SecretShare> GenerateSecretShares(
>       const SecretShareParameter& secret_share_parameter,
>       const std::vector<uint32_t>& input) = 0;
> ```

I think it is preferable to use absl::Span for read-only arrays.
___
*[`src/main/cc/any_sketch/crypto/secret_share.cc` line 92 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2U_gD2SmLiyjB7Eov:-Nm2U_gD2SmLiyjB7Eow:b91opyf) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/any_sketch/crypto/secret_share.cc#L92)):*
> ```cpp
>   for (int i = 0; i < input.size(); i++) {
>     share_vector[i] =
>         SubMod(input[i], share_vector[i], secret_share_parameter.modulus());
> ```

Do we need to check `input  < modulus`? `SumMod` has assumed that but it could be wrong by the caller.
___
*[`src/main/cc/any_sketch/crypto/secret_share.cc` line 106 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2V7WN2JPaHur1ZKCY:-Nm2V7WN2JPaHur1ZKCZ:bd8ofa2) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/any_sketch/crypto/secret_share.cc#L106)):*
> ```cpp
> 
> std::unique_ptr<SecretShareGenerator> CreateSecretShareGenerator() {
>   return absl::WrapUnique(new SecretShareGeneratorImpl());
> ```

A comment here to explain the usage of `new` like:
```
 // Using `new` to access a non-public constructor.
 ```
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 115 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2aK1J5CIWRo4lv8Fs:-Nm2aK1J5CIWRo4lv8Ft:b-6wyvt4) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/math/open_ssl_uniform_random_generator.cc#L115)):*
> ```cpp
>       (double)((1 << bit_length) - modulus) / (double)(1 << bit_length);
> 
>   // Compute the expected number of samples needed.
> ```

Can we add a comment to explain the choice of factor `2` here

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37)* status: all files reviewed, 7 unresolved discussions (waiting on @ple13)

___
*[`src/main/cc/any_sketch/crypto/secret_share.cc` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2gC4484Rijms-uC0h:-Nm2gC4484Rijms-uC0i:bugtg7b) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/any_sketch/crypto/secret_share.cc#L30)):*
> ```cpp
> using wfa::math::UniformPseudorandomGenerator;
> 
> uint32_t SubMod(uint32_t x, uint32_t y, uint32_t modulus) {
> ```

Put this in an unnamed namespace for internal linkage. See https://google.github.io/styleguide/cppguide.html#Internal_Linkage
___
*[`src/main/cc/math/uniform_pseudorandom_generator.h` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2h0307A3kMDX5BEoz:-Nm2h0307A3kMDX5BEp-:b-97l4nb) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/math/uniform_pseudorandom_generator.h#L46)):*
> ```objc
>       uint64_t size) = 0;
> 
>   // Generate a vector of pseudorandom values in the range [0, modulus).
> ```

nit: summary fragment for a function should be a verb phrase.



_Suggestion:_
```objc
Generates
```
___
*[`src/main/proto/wfa/any_sketch/secret_share.proto` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2hDVa62hovhc7M2Od:-Nm2hDVa62hovhc7M2Oe:bjkgt2d) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/proto/wfa/any_sketch/secret_share.proto#L31)):*
> ```proto
> }
> 
> message SecretShare {
> ```

Just double-checking why this is a protobuf. Is it so we can use the same structure from the Java impl?

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37)* status: all files reviewed, 13 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/cc/any_sketch/crypto/secret_share.h` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2doTP7m7VeQxJVgDQ:-Nm2doTP7m7VeQxJVgDR:b-hen2de) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/any_sketch/crypto/secret_share.h#L28)):*
> ```objc
> namespace wfa::any_sketch::crypto {
> 
> class SecretShareGenerator {
> ```

Either this class should be stateful and conform to Unary function, or there should just be a namespace level function called "GenerateSecretShares." Having a class a a builder pattern for a stateless object isn't buying you anything here.
___
*[`src/main/cc/any_sketch/crypto/secret_share.cc` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2ruOW0oNWMwXacM5J:-Nm2ruOW0oNWMwXacM5K:bt3yo88) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/any_sketch/crypto/secret_share.cc#L30)):*
> ```cpp
> using wfa::math::UniformPseudorandomGenerator;
> 
> uint32_t SubMod(uint32_t x, uint32_t y, uint32_t modulus) {
> ```

Please document this function.
___
*[`src/main/cc/any_sketch/crypto/secret_share.cc` line 90 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2sDD6B9o8sPhjde9f:-Nm2sDD6B9o8sPhjde9g:b-lzbrn0) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/any_sketch/crypto/secret_share.cc#L90)):*
> ```cpp
>                    prng->GetUniformRandomRange(
>                        input.size(), secret_share_parameter.modulus()));
>   for (int i = 0; i < input.size(); i++) {
> ```

If you think it's worth reusing share_vector vs. having two vectors, one to represent the outputs and the other the random sequence, then a comment indicating that the values of share vector are initially the random sequence and are then replaced by the result of SubMod will be helpful for future readers.
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 92 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2oVlq0Uo3ru4L7JVI:-Nm2oVlq0Uo3ru4L7JVJ:b-89y77o) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/math/open_ssl_uniform_random_generator.h#L92)):*
> ```objc
> 
>   // Generate a vector of pseudorandom values in the range [0, modulus).
>   // First, we sample n random values in [0, 2^k) where k is the smallest value
> ```

"size" random values?
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 118 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2qX3XBgpJVL0852DP:-Nm2qX3Y719wEAnKGpO9:b-sudkax) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/math/open_ssl_uniform_random_generator.cc#L118)):*
> ```cpp
>   uint64_t sample_size =
>       (uint64_t)(size + 2 * failure_rate * size / (1 - failure_rate));
>   std::vector<unsigned char> arr(sample_size * bytes_per_value, 0);
> ```

Any reason you can't call GetPseudradomBytes as a basis of this implementation?
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2pfo7DSLTfraLjHMA:-Nm2pfo7DSLTfraLjHMB:bkav5zj) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/math/open_ssl_uniform_random_generator.cc#L149)):*
> ```cpp
>   // In case the number of rejections is higher than expected, sample more
>   // random values in the range and append to the current result.
>   if (ret.size() < size) {
> ```

Why not just put a while loop around the above? 
___
*[`src/main/cc/math/uniform_pseudorandom_generator.h` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2h0307A3kMDX5BEoz:-Nm2qoOW7OVAvF6Ntk8D:b-phsicu) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/math/uniform_pseudorandom_generator.h#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: summary fragment for a function should be a verb phrase.
</blockquote></details>

Also with respect to the function names, in this PR Generate and Get seem to be used as synonyms. Can the functions just use one of these verbs?

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37)* status: 1 of 12 files reviewed, 12 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 92 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2oVlq0Uo3ru4L7JVI:-Nm3L_RG52rk5Pygkvgf:b-ht4siw) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/math/open_ssl_uniform_random_generator.h#L92)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

"size" random values?
</blockquote></details>

I updated the comment. n is a bit larger than size as a portion of values in [0, 2^k) will be rejected. I removed the algorithm description and moved it to the .cc file.
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 115 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2aK1J5CIWRo4lv8Fs:-Nm3AcHW18uSm6kpdwVp:b-5iiykb) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/math/open_ssl_uniform_random_generator.cc#L115)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Can we add a comment to explain the choice of factor `2` here
</blockquote></details>

Updated the comment. Remove the factor 2 as it's not needed.
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 118 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2qX3XBgpJVL0852DP:-Nm36AzD2l-LY1c2aTbc:b-n1rmee) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/math/open_ssl_uniform_random_generator.cc#L118)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Any reason you can't call GetPseudradomBytes as a basis of this implementation?
</blockquote></details>

Ah yeah, this is much better.
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2pfo7DSLTfraLjHMA:-Nm3D3hb0-zqCbRzW8Fy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/math/open_ssl_uniform_random_generator.cc#L149)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why not just put a while loop around the above?
</blockquote></details>

Done.
___
*[`src/main/cc/math/uniform_pseudorandom_generator.h` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2h0307A3kMDX5BEoz:-Nm3DByz8bv6OH6azHc2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/math/uniform_pseudorandom_generator.h#L46)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Also with respect to the function names, in this PR Generate and Get seem to be used as synonyms. Can the functions just use one of these verbs?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/any_sketch/secret_share.proto` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2hDVa62hovhc7M2Od:-Nm3ENfhEZsYeDfOtXsp:b-hzjt0q) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/proto/wfa/any_sketch/secret_share.proto#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just double-checking why this is a protobuf. Is it so we can use the same structure from the Java impl?
</blockquote></details>

Yes, I think this will be easier to pass data through the JNI via serialization/deserialization.
___
*[`src/main/cc/any_sketch/crypto/secret_share.h` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2doTP7m7VeQxJVgDQ:-Nm32uUs6qG6VvgtCl6g:b-4zbda8) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/any_sketch/crypto/secret_share.h#L28)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Either this class should be stateful and conform to Unary function, or there should just be a namespace level function called "GenerateSecretShares." Having a class a a builder pattern for a stateless object isn't buying you anything here.
</blockquote></details>

Fixed. The class was removed, and a simple function is used instead.
___
*[`src/main/cc/any_sketch/crypto/secret_share.h` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2SJq5BCCS4R9oB55b:-Nm332EQ90D2lBp9qsaT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/any_sketch/crypto/secret_share.h#L39)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I think it is preferable to use absl::Span for read-only arrays.
</blockquote></details>

Done.
___
*[`src/main/cc/any_sketch/crypto/secret_share.cc` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2gC4484Rijms-uC0h:-Nm334gABy0PgVY5oEqR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/any_sketch/crypto/secret_share.cc#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Put this in an unnamed namespace for internal linkage. See https://google.github.io/styleguide/cppguide.html#Internal_Linkage
</blockquote></details>

Done.
___
*[`src/main/cc/any_sketch/crypto/secret_share.cc` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2ruOW0oNWMwXacM5J:-Nm34kiUDRMxXLalNs6q:b-6vorr0) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/any_sketch/crypto/secret_share.cc#L30)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please document this function.
</blockquote></details>

Commend added.
___
*[`src/main/cc/any_sketch/crypto/secret_share.cc` line 90 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2sDD6B9o8sPhjde9f:-Nm3GA5O9c7ekJzMtml9:b-k7ssbd) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/any_sketch/crypto/secret_share.cc#L90)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

If you think it's worth reusing share_vector vs. having two vectors, one to represent the outputs and the other the random sequence, then a comment indicating that the values of share vector are initially the random sequence and are then replaced by the result of SubMod will be helpful for future readers.
</blockquote></details>

Two vectors are now used to make the code clearer.
___
*[`src/main/cc/any_sketch/crypto/secret_share.cc` line 92 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2U_gD2SmLiyjB7Eov:-Nm35sPTEt8YByhJRJLd:b8i4phb) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/any_sketch/crypto/secret_share.cc#L92)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Do we need to check `input  < modulus`? `SumMod` has assumed that but it could be wrong by the caller.
</blockquote></details>

Added the checks for the SubMod function.
___
*[`src/main/cc/any_sketch/crypto/secret_share.cc` line 106 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm2V7WN2JPaHur1ZKCY:-Nm34tjT7wk7iZOw8BtG:blyrcnj) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/e22968b82d894f916e77cfc9dd4bd5399b5b0e48/src/main/cc/any_sketch/crypto/secret_share.cc#L106)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

A comment here to explain the usage of `new` like:
```
 // Using `new` to access a non-public constructor.
 ```
</blockquote></details>

Class has been removed.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37)* status: all files reviewed, 7 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 91 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm7Yjum54iExyErejP6:-Nm7Yjum54iExyErejP7:b-ivpcoo) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/6a01d5b71416bf7dbbc9f789c84613830977e058/src/main/cc/math/open_ssl_uniform_random_generator.cc#L91)):*
> ```cpp
> }
> 
> // Rejection sampling is used to generate uniformly random values in the range
> ```

nit: the first line of a function comment should be a summary fragment, specifically a verb phrase.

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37)* status: 11 of 12 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 91 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-Nm7Yjum54iExyErejP6:-NmCj7YJ9DI0ctcepUXo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/6a01d5b71416bf7dbbc9f789c84613830977e058/src/main/cc/math/open_ssl_uniform_random_generator.cc#L91)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: the first line of a function comment should be a summary fragment, specifically a verb phrase.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 9 of 11 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13)

___
*[`src/test/cc/any_sketch/crypto/secret_share_generator_test.cc` line 65 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-NnKsD907ccJ06Y57skn:-NnKsD907ccJ06Y57sko:bmzulur) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/36f39ace27e51bd6737b1c5a642c4e7f9a912054/src/test/cc/any_sketch/crypto/secret_share_generator_test.cc#L65)):*
> ```cpp
>       std::unique_ptr<UniformPseudorandomGenerator> prng,
>       OpenSslUniformPseudorandomGenerator::Create(key_vec, iv_vec));
> ```

nit: ASSERT_EQ(input.size(), secret_share.share_vector.size())

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/test/cc/any_sketch/crypto/secret_share_generator_test.cc` line 65 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37#-NnKsD907ccJ06Y57skn:-NnPRZIp3kx26DeAH-2c:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/36f39ace27e51bd6737b1c5a642c4e7f9a912054/src/test/cc/any_sketch/crypto/secret_share_generator_test.cc#L65)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

nit: ASSERT_EQ(input.size(), secret_share.share_vector.size())
</blockquote></details>

Done

**Review by benjaminkreuter — APPROVED** [review]

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 12 files at r2, 8 of 11 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/37)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
