### PR TITLE
Added a name to the any-sketch workspace

### PR DESCRIPTION
**Pull request by enfreck**
Add the name "any_sketch" to the any-sketch workspace

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/8)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/8)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck and @stevenwarejones)

___
*[WORKSPACE, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/8#-MdIH4Y04XEhpqUz-nzB:-MdIH4Y04XEhpqUz-nzC:b-bwsyr3) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/01a05eb2866108e6157f23c9de4400589a366bc1/WORKSPACE#L1)):*
> ```
> wfa_any_sketch
> ```
The name should match the one we're using to import this into other workspaces. So far we've been using `any_sketch`. 

Is there an intent to update the name in the workspaces that import this one, or do we just want to go with `any_sketch` for the name? I know that we don't have much consistency here at the moment.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/8)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck and @stevenwarejones)

___
*[WORKSPACE, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/8#-MdIH4Y04XEhpqUz-nzB:-MdILJIf1H9fqaxjj5jy:b-v3tjkt) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/01a05eb2866108e6157f23c9de4400589a366bc1/WORKSPACE#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> wfa_any_sketch
> ```
The name should match the one we're using to import this into other workspaces. So far we've been using `any_sketch`. 

Is there an intent to update the name in the workspaces that import this one, or do we just want to go with `any_sketch` for the name? I know that we don't have much consistency here at the moment.
</blockquote></details>

`any_sketch` sounds fine. @enfreck can you please update it to just `any_sketch`? Thanks

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/8)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/8)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck)

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/8)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck)

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/8)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[WORKSPACE, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/8#-MdIH4Y04XEhpqUz-nzB:-MdIUTWw5ZBXCDe7z072:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/01a05eb2866108e6157f23c9de4400589a366bc1/WORKSPACE#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`any_sketch` sounds fine. @enfreck can you please update it to just `any_sketch`? Thanks
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Pull request merged**
