### PR TITLE
Create GetDistributedDiscreteGaussianRandomComponent

### PR DESCRIPTION
**Pull request by iverson52000**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19)

### CODE REVIEW

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @iverson52000)

___
*[`src/main/cc/any_sketch/crypto/sketch_encrypter.cc` line 98 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19#-NJq8Cl1AnVEDZD9gKwh:-NJq8Cl1AnVEDZD9gKwi:b-dkj9g) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/d4a58597c708720b9d3d677a39bfeb3e8d401e15/src/main/cc/any_sketch/crypto/sketch_encrypter.cc#L98)):*
> ```cpp
>   ~SketchEncrypterImpl() override = default;
> 
>   SketchEncrypterImpl(SketchEncrypterImpl &&other) = delete;
> ```

Please remove all formatting changes.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 8 of 15 files at r1, 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19)* status: 12 of 18 files reviewed, 9 unresolved discussions (waiting on @iverson52000)

___
*[`WORKSPACE` line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19#-NJv0B6WAUKKkU0aP_Nr:-NJv0B6WAUKKkU0aP_Ns:b-wkwcy0) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/2f6f83cae4f199c6d2298dede1f6621ffd860f01/WORKSPACE#L26)):*
> ```Starlark
> grpc_deps()
> 
> load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
> ```

I don't see where we're picking this up anywhere else.
___
*[`build/any_sketch_extra_deps.bzl` line 16 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19#-NJv0YJRD_ptcgZr7s7q:-NJv0YJS7kxhcaIx76bb:b-jaexn9) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/3ff627e697fefe75fc2a1eee736d50df6ec48f37/build/any_sketch_extra_deps.bzl#L16)):*
> ```Starlark
> 
> """
> Runs external macros necessary for any-sketch.
> ```

"any-sketch transitive dependencies"?
___
*[`build/any_sketch_repositories.bzl` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19#-NJv1K2m5m0XS3id8Xv8:-NJv0jg71d6eWIw2zT8F:bgwwbxl) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/3ff627e697fefe75fc2a1eee736d50df6ec48f37/build/any_sketch_repositories.bzl#L1)):*
> ```Starlark
> # Copyright 2022 The Cross-Media Measurement Authors
> ```

Add to common_cpp instead of a new file?
___
*[`src/main/cc/any_sketch/crypto/sketch_encrypter.cc` line 223 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19#-NJv2iZbAEc8nc7KYn03:-NJv2iZbAEc8nc7KYn04:blzumdb) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/3ff627e697fefe75fc2a1eee736d50df6ec48f37/src/main/cc/any_sketch/crypto/sketch_encrypter.cc#L223)):*
> ```cpp
>   params.set_delta(publisher_noise_parameter.delta());
> 
>   // TODO(alberthsuu): Pass in a flag to toggle between different noise
> ```

I don't see any changes of substance in this file. Please revert the changes to this file.
___
*[`src/main/cc/math/distributions.h` line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19#-NJv3ILN04aL8GZz02Ga:-NJv3ILN04aL8GZz02Gb:b-hyxcfg) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/3ff627e697fefe75fc2a1eee736d50df6ec48f37/src/main/cc/math/distributions.h#L23)):*
> ```objc
> namespace wfa::math {
> 
> struct DistributedRandomComponentOptions {
> ```

I don't like the idea of combining the parameters for the geometric and laplace mechanisms into one struct. We need to find a way to separate the gaussian and polya options cleanly.
___
*[`src/main/cc/math/distributions.cc` line 80 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19#-NJv3ggk1xlfF815gmik:-NJv3ggk1xlfF815gmil:b-ifg1l1) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/3ff627e697fefe75fc2a1eee736d50df6ec48f37/src/main/cc/math/distributions.cc#L80)):*
> ```cpp
> }
> 
> absl::StatusOr<int64_t> GetDistributedDiscreteGaussianRandomComponent(
> ```

Please add @pasin30055 to review this function.
___
*[`src/main/cc/math/distributions.cc` line 82 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19#-NJv3QMQ8Yi0TpA-ERoI:-NJv3QMQ8Yi0TpA-ERoJ:b-lznjqq) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/3ff627e697fefe75fc2a1eee736d50df6ec48f37/src/main/cc/math/distributions.cc#L82)):*
> ```cpp
> absl::StatusOr<int64_t> GetDistributedDiscreteGaussianRandomComponent(
>     DistributedRandomComponentOptions options) {
>   std::cout << "Generating discrete Gaussian noise..." << std::endl;
> ```

Please remove the debug message.
___
*[`src/main/cc/math/noise_parameters_computation.cc` line 14 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19#-NJv3zPqCADihwktRVfN:-NJv3zPqCADihwktRVfO:b-ycdm7h) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/3ff627e697fefe75fc2a1eee736d50df6ec48f37/src/main/cc/math/noise_parameters_computation.cc#L14)):*
> ```cpp
> // See the License for the specific language governing permissions and
> // limitations under the License.
> #include "math/noise_parameters_computation.h"
> ```

Remove white space changes.

**Comment by iverson52000** [comment]
Thanks @kungfucraig for all the comments! This PR is still WIP and will address them later on

**Review by iverson52000 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19)* status: 7 of 18 files reviewed, 9 unresolved discussions (waiting on @kungfucraig)

___
*[`build/any_sketch_extra_deps.bzl` line 16 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19#-NJv0YJRD_ptcgZr7s7q:-NKKfJlgCaNuuqCaGbtC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/3ff627e697fefe75fc2a1eee736d50df6ec48f37/build/any_sketch_extra_deps.bzl#L16)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

"any-sketch transitive dependencies"?
</blockquote></details>

Done.
___
*[`build/any_sketch_repositories.bzl` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19#-NJv1K2m5m0XS3id8Xv8:-NKKfJAB2YSTFg6CeC6-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/3ff627e697fefe75fc2a1eee736d50df6ec48f37/build/any_sketch_repositories.bzl#L1)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Add to common_cpp instead of a new file?
</blockquote></details>

Done.

**Comment by iverson52000** [comment]
*[`src/main/cc/math/distributions.cc` line 80 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/19#-NJv3ggk1xlfF815gmik:-NKOvs_WAaoe5FSl0D35:bs9mqai) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/3ff627e697fefe75fc2a1eee736d50df6ec48f37/src/main/cc/math/distributions.cc#L80)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please add @pasin30055 to review this function.
</blockquote></details>

This function is based on the implementation in https://github.com/world-federation-of-advertisers/cardinality_estimation_evaluation_framework/blob/master/src/common/noisers.py#L207

**Pull request closed without merging**
