### PR TITLE
Update common-cpp to v0.10.0

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/28)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Comment by iverson52000** [comment]
No external approval?

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/28)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by stevenwarejones — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/28#-:-NUYX2Ns-LSk9aiF1zcI:b593w57)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
