### PR TITLE
Migrate to Fingerprinter in common-cpp

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/11)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/11)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @wangyaopw)

___
*[WORKSPACE, line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/11#-Me5mq8c5z3sC95AHhSc:-Me5mq8c5z3sC95AHhSd:bydqzkl) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/abc665bbc1ae1f4b1a53b2c812b737f28a0fe35f/WORKSPACE#L80)):*
> ```Starlark
> )
> 
> new_git_repository(
> ```

TODO: delete this after https://github.com/world-federation-of-advertisers/common-cpp/pull/3 lands (and pull the deps in from that instead).

**Review by wangyaopw — APPROVED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/11)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck and @stevenwarejones)

**Review by enfreck — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/11)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/test/cc/estimation/estimators_test.cc, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/11#-Me6ku1U4daZ8BlhYxIB:-Me6ku1U4daZ8BlhYxIC:b-cwri35) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/abc665bbc1ae1f4b1a53b2c812b737f28a0fe35f/src/test/cc/estimation/estimators_test.cc#L59)):*
> ```cpp
>   absl::flat_hash_set<int64_t> indexes;
> 
>   const Fingerprinter& fingerprinter = GetSha256Fingerprinter();
> ```

If this file is in any-sketch and Fingerprinter is in common-app, would a path name be needed?
___
*[src/test/cc/estimation/estimators_test.cc, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/11#-Me6hi132iZSZEK1Dn0b:-Me6hi132iZSZEK1Dn0c:bmhgz7l) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/abc665bbc1ae1f4b1a53b2c812b737f28a0fe35f/src/test/cc/estimation/estimators_test.cc#L61)):*
> ```cpp
>   const Fingerprinter& fingerprinter = GetSha256Fingerprinter();
>   std::unique_ptr<Distribution> exponential_distribution =
>       wfa::any_sketch::GetExponentialDistribution(&fingerprinter, decay_rate,
> ```

Does this need to be fully qualified?  Or is that just for using definitions?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/11)* status: all files reviewed, 3 unresolved discussions (waiting on @enfreck and @stevenwarejones)

___
*[src/test/cc/estimation/estimators_test.cc, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/11#-Me6ku1U4daZ8BlhYxIB:-Me6sF9u-vvveBk6o36X:b-af1b6p) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/abc665bbc1ae1f4b1a53b2c812b737f28a0fe35f/src/test/cc/estimation/estimators_test.cc#L59)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

If this file is in any-sketch and Fingerprinter is in common-app, would a path name be needed?
</blockquote></details>

Fingerprinter is in the wfa root namespace, so no path name is needed.
___
*[src/test/cc/estimation/estimators_test.cc, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/11#-Me6hi132iZSZEK1Dn0b:-Me6sVfN4bRvtR2sBWsz:b-j2t5t7) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/abc665bbc1ae1f4b1a53b2c812b737f28a0fe35f/src/test/cc/estimation/estimators_test.cc#L61)):*
> ```
> wfa::any_sketch::GetExponentialDistribution
> ```
wfa::any_sketch::GetExponentialDistribution or any_sketch::GetExponentialDistribution both work I think.

**Review by enfreck — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/11)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 11 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/11)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

**Pull request merged**
