### PR TITLE
Update bazel version to 7.0.1

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/46)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/46)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/46#-NrfykHaDQYig542dyL8:-NrfykHb5_MygJ-Uexoc:b-j7fcj0) (no related file):*
Also update the build-test workflow to check the lock file. See https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/200

___

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/46)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/46#-NrfykHaDQYig542dyL8:-NrgKsYoEAcLGmfXL0_A:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Also update the build-test workflow to check the lock file. See https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/200
</blockquote></details>

Done.

___

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/46)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/46)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
