### PR TITLE
Expose NoiseComponentOptions from a Noiser by getNoiseOptions()

### PR DESCRIPTION
**Pull request by renjiezh**
In order to achieve:
```
// Initialize.
auto noiser = math::DistributedDiscreteGaussianNoiser(BuildDiscreteGaussianNoiseOptions(params, count));

// Use const accessor for options.
auto foo = noiser.options();
```
In PR (https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/917)

Co-authored-by: @SanjayVas

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22)* status: all files reviewed, 3 unresolved discussions (waiting on @iverson52000, @kungfucraig, and @renjiezh)

___
*[`.github/workflows/build-test.yml` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22#-NS88pWM1f24zreDKmpv:-NS88pWM1f24zreDKmpw:bu86k2m) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/6d6a690878d0dc68f89afd1df6ebfa1bf480cb82/.github/workflows/build-test.yml#L28)):*
> ```YAML
>   build-test:
>     name: Build and test
>     runs-on: ubuntu-20.04
> ```

Let's put this change in a separate PR. I know it'll block submission of this PR, so you'll have to do it as a chain of dependent PRs.
___
*[`src/main/cc/math/distributed_geometric_noiser.h` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22#-NS8AI074X7qY2aLcRrx:-NS8AI074X7qY2aLcRry:b-9htoxy) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/6d6a690878d0dc68f89afd1df6ebfa1bf480cb82/src/main/cc/math/distributed_geometric_noiser.h#L42)):*
Accessors get named like variables[^1].

> For example, `int count()` and `void set_count(int count)`.

[^1]: https://google.github.io/styleguide/cppguide.html#Function_Names



_Suggestion:_
```objc
options()
```
___
*[`src/main/cc/math/distributed_noiser.h` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22#-NS8BiwU6vgJIgab519P:-NS8BiwU6vgJIgab519Q:brl1eay) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/6d6a690878d0dc68f89afd1df6ebfa1bf480cb82/src/main/cc/math/distributed_noiser.h#L49)):*
> ```objc
>   [[nodiscard]] virtual absl::StatusOr<int64_t> GenerateNoiseComponent()
>       const = 0;
>   [[nodiscard]] virtual const NoiseComponentOptions& getNoiseOptions()
> ```

You'll want to template this so that each implementation can return the correct subtype of `NoiseComponentOptions`. This would mean that e.g. `DistributedGeometricNoiser` would inherit from `DistributedNoiser<DistributedGeometricNoiseComponentOptions>`.



_Suggestion:_
```objc
virtual const T& options()
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @iverson52000, @kungfucraig, and @SanjayVas)

___
*[`.github/workflows/build-test.yml` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22#-NS88pWM1f24zreDKmpv:-NSC54wR049sJ_pgMEoE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/6d6a690878d0dc68f89afd1df6ebfa1bf480cb82/.github/workflows/build-test.yml#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Let's put this change in a separate PR. I know it'll block submission of this PR, so you'll have to do it as a chain of dependent PRs.
</blockquote></details>

Done.
___
*[`src/main/cc/math/distributed_geometric_noiser.h` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22#-NS8AI074X7qY2aLcRrx:-NSC56s329aQBtpWOQQ_:b-kdmxcz) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/6d6a690878d0dc68f89afd1df6ebfa1bf480cb82/src/main/cc/math/distributed_geometric_noiser.h#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Accessors get named like variables[^1].

> For example, `int count()` and `void set_count(int count)`.

[^1]: https://google.github.io/styleguide/cppguide.html#Function_Names
</blockquote></details>

Done.
Thanks for letting me know.
___
*[`src/main/cc/math/distributed_noiser.h` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22#-NS8BiwU6vgJIgab519P:-NSC5EHV-9DQgAnhauKS:b-4g4v50) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/6d6a690878d0dc68f89afd1df6ebfa1bf480cb82/src/main/cc/math/distributed_noiser.h#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You'll want to template this so that each implementation can return the correct subtype of `NoiseComponentOptions`. This would mean that e.g. `DistributedGeometricNoiser` would inherit from `DistributedNoiser<DistributedGeometricNoiseComponentOptions>`.
</blockquote></details>

As I only want to expose it as the type of base class `NoiseComponentOptions`, seems no need to use template here.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @iverson52000 and @SanjayVas)

**Review by iverson52000 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @iverson52000, @kungfucraig, and @SanjayVas)

___
*[`src/main/cc/math/distributed_noiser.h` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22#-NS8BiwU6vgJIgab519P:-NSHsdDP6np8rfSnugSJ:b4vg9le) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/6d6a690878d0dc68f89afd1df6ebfa1bf480cb82/src/main/cc/math/distributed_noiser.h#L49)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

As I only want to expose it as the type of base class `NoiseComponentOptions`, seems no need to use template here. 
</blockquote></details>

Updated based on https://github.com/world-federation-of-advertisers/any-sketch/pull/24.
Thanks a lot!

**Review by SanjayVas — APPROVED** [review]
> Reviewed 8 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh)

___
*[`src/test/cc/math/distributed_discrete_gaussian_noiser_test.cc` line 276 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22#-NSIWVd5ACyUIH_CpbRs:-NSIWVd5ACyUIH_CpbRt:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/4f23615b839d9c955ede1b606ea3713e970c5107/src/test/cc/math/distributed_discrete_gaussian_noiser_test.cc#L276)):*
> ```cpp
>   DistributedDiscreteGaussianNoiser distributed_discrete_gaussian_noiser(
>       options);
>   auto const_noise_options = distributed_discrete_gaussian_noiser.options();
> ```

nit



_Suggestion:_
```cpp
const auto&
```
___
*[`src/test/cc/math/distributed_geometric_noiser_test.cc` line 112 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22#-NSIWftp8edRpJgsa7md:-NSIWftp8edRpJgsa7me:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/4f23615b839d9c955ede1b606ea3713e970c5107/src/test/cc/math/distributed_geometric_noiser_test.cc#L112)):*
> ```cpp
>       contributor_count, p, truncate_threshold, shift_offset};
>   auto distributed_geometric_noiser = DistributedGeometricNoiser(options);
>   auto const_noise_options = distributed_geometric_noiser.options();
> ```

nit



_Suggestion:_
```cpp
const auto&
```

**Review by renjiezh — COMMENTED** [review]
> Reviewed 6 of 8 files at r4, 2 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
