### PR TITLE
Update github workflows to use Ubuntu-20.04

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @stevenwarejones)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/23)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @renjiezh, and @stevenwarejones)

___
*[`.github/workflows/build-test.yml` line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/23#-NSCSPja2EQfxpFEQigv:-NSCSPja2EQfxpFEQigw:b-fr6y5d) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/549f1e23eb1f560fcfe86e322dead7d320eab89c/.github/workflows/build-test.yml#L34)):*
> ```YAML
> 
>       - name: Bazel build and test
>         uses: world-federation-of-advertisers/actions/bazel-build-test@v1.3.0
> ```

Swap this to use the floating `v1` release while you're at it.



_Code quote:_
```YAML
v1.3.0
```

**Review by Marco-Premier — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/23)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`.github/workflows/build-test.yml` line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/23#-NSCSPja2EQfxpFEQigv:-NSFnBrG1H8NRjIR5RYx:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/549f1e23eb1f560fcfe86e322dead7d320eab89c/.github/workflows/build-test.yml#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Swap this to use the floating `v1` release while you're at it.
</blockquote></details>

+1

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/23)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`.github/workflows/build-test.yml` line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/23#-NSCSPja2EQfxpFEQigv:-NSHtYJ82kN9fYJHBUrm:bu4ozr6) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/549f1e23eb1f560fcfe86e322dead7d320eab89c/.github/workflows/build-test.yml#L34)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
Thanks.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Comment by SanjayVas** [comment]
This breaks the build and test workflow. It passed here due to using fully cached results. The fix forward is in #25.

**Pull request merged**
