### PR TITLE
Migrated testutil to common_cpp

### PR DESCRIPTION
**Pull request by enfreck**
Migrated testutil to common-cpp/src/main/cc/common_cpp/testing/

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/14)

### CODE REVIEW

**Review by jmorrrr — APPROVED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Review by jmorrrr — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by efoxepstein — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/14#-:-MfAUSWL5NP2f9movtRB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 10 of 15 files at r1, 5 of 5 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 5 of 7 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Pull request merged**
