### PR TITLE
build: Update dependency versions, fixing build warnings

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/51)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/51)* status: 8 of 9 files reviewed, all discussions resolved

**Review by Marco-Premier — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/51)* status: 8 of 9 files reviewed, all discussions resolved

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/51)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
