### PR TITLE
Modify include in fingerprinter.cc

### PR DESCRIPTION
**Pull request by enfreck**
Remove 'external/farmhash/' from 'external/farmhash/src/farmhash.h'

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/10)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/10#-:-MddDgd6D1yA-swM2c81:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/10)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck and @oliver-amzn)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/10#-Me-hyDk9kxPR9CNM6Ba:-Me-hyDl4AUv4nmx40VD:b-2gbsvg) (no related file):*
Note: since https://github.com/world-federation-of-advertisers/any-sketch/pull/9 was merged, the path to `fingerprinters.cc` has changed. This will likely result in a merge conflict when you pull to rebase this PR.

---

**Comment by enfreck** [comment]
Restarting pull request with updated paths to fingerprinter.

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/10)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/10#-Me-hyDk9kxPR9CNM6Ba:-Me0TmB88hMJQE53Uenm:b-896fix) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Note: since https://github.com/world-federation-of-advertisers/any-sketch/pull/9 was merged, the path to `fingerprinters.cc` has changed. This will likely result in a merge conflict when you pull to rebase this PR.
</blockquote></details>

Done.

---

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Pull request merged**
