### PR TITLE
Add unit test for sketches with empty values.

### PR DESCRIPTION
**Pull request by renjiezh**
With new MPC protocol Reach-Only LLV2, registers in sketches only have index without any values. The test units are added to verify that sketches without values are able to be created and encrypted successfully.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @iverson52000, @ple13, and @renjiezh)

___
*[`src/test/cc/any_sketch/crypto/sketch_encrypter_test.cc` line 214 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29#-NXCOM3G89nFVNQfimLa:-NXCOM3G89nFVNQfimLb:b-h4aof5) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/cacca10034b7aba8d540709cd149ce2121da6899/src/test/cc/any_sketch/crypto/sketch_encrypter_test.cc#L214)):*
> ```cpp
> 
> TEST_F(SketchEncrypterTest, EncryptionOfEmptyValuesShouldBeComplete) {
>   const int register_size = 1000;
> ```

Probably want to call this "register_count". The "66" you have below would be the "encrypted register size", which you should make a variable for as it helps document the code.
___
*[`src/test/cc/any_sketch/crypto/sketch_encrypter_test.cc` line 218 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29#-NXCOeA4DcPIEM95cxr6:-NXCOeA4DcPIEM95cxr7:b-vsehwj) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/cacca10034b7aba8d540709cd149ce2121da6899/src/test/cc/any_sketch/crypto/sketch_encrypter_test.cc#L218)):*
> ```cpp
>   Sketch plain_sketch;
>   *plain_sketch.mutable_config() =
>       CreateSketchConfig(/* unique_cnt = */ 0, /* sum_cnt = */ 0);
> ```

Can you describe what is being created here?

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @iverson52000, @ple13, and @renjiezh)

___
*[`src/test/cc/any_sketch/any_sketch_test.cc` line 157 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29#-NXCOzxi6mY90NHqiPhq:-NXCOzxi6mY90NHqiPhr:b-czexg3) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/cacca10034b7aba8d540709cd149ce2121da6899/src/test/cc/any_sketch/any_sketch_test.cc#L157)):*
> ```cpp
> TEST(AnySketchTest, EmptyValues) {
>   std::vector<ValueFunction> value_functions;
>   AnySketch sketch(MakeFakeDistributionIndex(), std::move(value_functions));
> ```

You probably shouldn't call move here, but instead have the constructor take the value_functions as a const& 

cc: @SanjayVas you agree?

**Review by kungfucraig — COMMENTED** [review]
I totally understand why you're writing these tests - to see what if any work we need to do to support the reach-only protocol, but could you add that to the description of the PR?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29#-:-NXCPD--7VAy0YvwxR5c:bh4jn7a)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @iverson52000, @ple13, and @renjiezh)

**Review by renjiezh — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29#-:-NXCUdluB2388sz7x7kY:b-ucfknh)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @iverson52000, @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/test/cc/any_sketch/any_sketch_test.cc` line 157 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29#-NXCOzxi6mY90NHqiPhq:-NXCRvqj6uy1mCVUUy3L:b-dh5hh0) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/cacca10034b7aba8d540709cd149ce2121da6899/src/test/cc/any_sketch/any_sketch_test.cc#L157)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

You probably shouldn't call move here, but instead have the constructor take the value_functions as a const& 

cc: @SanjayVas you agree?
</blockquote></details>

`ValueFunction` contains unique_ptr. And the constructor `sketch()` doesn't accept reference of the vector. Thus have to move.
But never mind, I changed it to avoid using `move`.
___
*[`src/test/cc/any_sketch/crypto/sketch_encrypter_test.cc` line 214 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29#-NXCOM3G89nFVNQfimLa:-NXCUbOU89gsYm9xQe6V:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/cacca10034b7aba8d540709cd149ce2121da6899/src/test/cc/any_sketch/crypto/sketch_encrypter_test.cc#L214)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Probably want to call this "register_count". The "66" you have below would be the "encrypted register size", which you should make a variable for as it helps document the code.
</blockquote></details>

Done.
___
*[`src/test/cc/any_sketch/crypto/sketch_encrypter_test.cc` line 218 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29#-NXCOeA4DcPIEM95cxr6:-NXCUbz-68UhEjh7fkAI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/cacca10034b7aba8d540709cd149ce2121da6899/src/test/cc/any_sketch/crypto/sketch_encrypter_test.cc#L218)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you describe what is being created here?
</blockquote></details>

Done.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @iverson52000, @kungfucraig, and @ple13)

___
*[`src/test/cc/any_sketch/any_sketch_test.cc` line 157 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29#-NXCOzxi6mY90NHqiPhq:-NXCPd8XC4G8ssF_wgDJ:b-mrdy0j) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/cacca10034b7aba8d540709cd149ce2121da6899/src/test/cc/any_sketch/any_sketch_test.cc#L157)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

`ValueFunction` contains unique_ptr. And the constructor `sketch()` doesn't accept reference of the vector. Thus have to move.
But never mind, I changed it to avoid using `move`.
</blockquote></details>

Hmm, so it looks like AnySketch instances keep their own copies of the collections, but as absl::FixedArray instances. I'm not entirely certain why it does this. It also takes ownership of the contents, which is why I believe the const reference doesn't work.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000 and @ple13)

___
*[`src/test/cc/any_sketch/any_sketch_test.cc` line 157 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29#-NXCOzxi6mY90NHqiPhq:-NXCcobCEI9iLf_ouHyX:b-5d0tlq) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/cacca10034b7aba8d540709cd149ce2121da6899/src/test/cc/any_sketch/any_sketch_test.cc#L157)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Hmm, so it looks like AnySketch instances keep their own copies of the collections, but as absl::FixedArray instances. I'm not entirely certain why it does this. It also takes ownership of the contents, which is why I believe the const reference doesn't work.
</blockquote></details>

Okay, I didn't look at the implementation of AnySketch, just the signature. 

Sending the empty vector by value seems fine and we can leave AnySketch alone.

**Review by iverson52000 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @ple13)

**Review by renjiezh — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @ple13)

**Pull request merged**
