### PR TITLE
Add function to sample non zero random vector.

### PR DESCRIPTION
**Pull request by ple13**

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/49)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/cc/math/uniform_pseudorandom_generator.h` line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/49#-Nwl4L470C-Q0TW79cFf:-Nwl4L470C-Q0TW79cFg:b-79o0yq) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/f9123ef698bbe4537f3662605f4606c02431fb2c/src/main/cc/math/uniform_pseudorandom_generator.h#L50)):*
> ```objc
>       int64_t size, uint32_t modulus) = 0;
> 
>   // Generates uniformly random values in the range [1, modulus).
> ```

nit: shouldn't this have the same summary fragment as `GenerateUniformRandomRange`, only including the non-zero part?

**Review by kungfucraig — APPROVED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/49)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @renjiezh)

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/49)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/cc/math/uniform_pseudorandom_generator.h` line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/49#-Nwl4L470C-Q0TW79cFf:-NwlQ0tGAv_-UWungPYW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/f9123ef698bbe4537f3662605f4606c02431fb2c/src/main/cc/math/uniform_pseudorandom_generator.h#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: shouldn't this have the same summary fragment as `GenerateUniformRandomRange`, only including the non-zero part?
</blockquote></details>

Done.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/49)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh, @SanjayVas, and @stevenwarejones)

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/49)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 166 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/49#-NwouvD-3FbtO9p4KX5y:-NwouvD-3FbtO9p4KX5z:b-r6s9ls) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c4a5bfba0f36fdbcc3ce06ee449d72a21879eab0/src/main/cc/math/open_ssl_uniform_random_generator.cc#L166)):*
> ```cpp
>   }
> 
>   if (size < 0) {
> ```

in what scenario is size == 0 valid?

**Review by ple13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/49)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 166 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/49#-NwouvD-3FbtO9p4KX5y:-NwpbnDQ4Xak3akWQlxv:bx8vg8o) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c4a5bfba0f36fdbcc3ce06ee449d72a21879eab0/src/main/cc/math/open_ssl_uniform_random_generator.cc#L166)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

in what scenario is size == 0 valid?
</blockquote></details>

Size = 0 is a singularity case, where the return is an empty array. I'm not sure if this will ever be used in practice, but it could happen when we call prng->GenerateNonZeroUniformRandomRange(otherArray.size()) where the otherArray is an empty one.

**Review by renjiezh — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/49)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

**Pull request merged**
