### PR TITLE
Replace absl::BitGen by OpenSSL's random library

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)

**Review by ple13 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @iverson52000, @kungfucraig, and @renjiezh)

___
*[`src/main/cc/math/openssl_random_generator.cc` line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTHgw_F3PQflJydEcQf:-NTHgw_F3PQflJydEcQg:b5mommy) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c52d29e18015eee76d3f0df57a532e32182d2c2e/src/main/cc/math/openssl_random_generator.cc#L20)):*
> ```cpp
> 
> uint64_t OpensslRandomGenerator::operator()() {
>   unsigned char bytes[64];
> ```

Should it be bytes[8]?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @iverson52000, @kungfucraig, and @ple13)

___
*[`src/main/cc/math/openssl_random_generator.cc` line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTHgw_F3PQflJydEcQf:-NTHuF2xEdjegQn0M-EO:b8go2vd) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c52d29e18015eee76d3f0df57a532e32182d2c2e/src/main/cc/math/openssl_random_generator.cc#L20)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Should it be bytes[8]?
</blockquote></details>

Good catch. Thanks!

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @iverson52000, @ple13, and @renjiezh)

___
*[`src/main/cc/math/openssl_random_generator.h` line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTK3o-VAH-CsBhe51Oh:-NTK3mZP6fRUrJtbL5vr:bkpk3nv) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/6448b8741eafb2ee2a741e4f23cc7bd447a3e317/src/main/cc/math/openssl_random_generator.h#L26)):*
> ```objc
> namespace wfa::math {
> 
> class OpensslRandomGenerator : public std::uniform_int_distribution<uint64_t> {
> ```

I think you can do this without inheritance by just conforming to: 
https://en.cppreference.com/w/cpp/named_req/UniformRandomBitGenerator

Also, can you call this class OpenSslUniformRandomGenerator ?



_Code quote:_
```objc
class OpensslRandomGenerator : public std::uniform_int_distribution<uint64_t> {
  static const int MAX_ATTEMPTS = 10;
```
___
*[`src/main/cc/math/openssl_random_generator.cc` line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTHgw_F3PQflJydEcQf:-NTK4AzD7i4nxxt-RMMY:bc3kxf9) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c52d29e18015eee76d3f0df57a532e32182d2c2e/src/main/cc/math/openssl_random_generator.cc#L20)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Good catch. Thanks!
</blockquote></details>

This should be unsigned char bytes[sizeof(uint64_t)]

**Review by iverson52000 — COMMENTED** [review]
Cool! Does `OpensslRandomGenerator` supports reseeding?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-:-NTKCuZ7Et8LLny7NNrw:b-i6ktlj)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

**Review by renjiezh — COMMENTED** [review]
It can be done but not required. By default it uses the OS's randomness to seed automatically. For deterministic test purpose, we would modify the API for a bit to allow other types of randomness generator.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-:-NTKS0-l9U1YI4_m9oq8:bcl5swu)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`src/main/cc/math/openssl_random_generator.h` line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTK3o-VAH-CsBhe51Oh:-NTKOnLMEbhX800HgOKr:b-u3cutu) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/6448b8741eafb2ee2a741e4f23cc7bd447a3e317/src/main/cc/math/openssl_random_generator.h#L26)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think you can do this without inheritance by just conforming to: 
https://en.cppreference.com/w/cpp/named_req/UniformRandomBitGenerator

Also, can you call this class OpenSslUniformRandomGenerator ?
</blockquote></details>

Thanks for the hint. By adding "result_type", I can finally remove the inheritance.
Renamed.
___
*[`src/main/cc/math/openssl_random_generator.cc` line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTHgw_F3PQflJydEcQf:-NTKRz4i7k4XMa236PP_:b-83sjo4) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c52d29e18015eee76d3f0df57a532e32182d2c2e/src/main/cc/math/openssl_random_generator.cc#L20)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This should be unsigned char bytes[sizeof(uint64_t)]
</blockquote></details>

Nice.

**Review by ple13 — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig)

**Review by iverson52000 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 4 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13)

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTLOfN78oxqoFg8oFAp:-NTLOfN78oxqoFg8oFAq:blf28tj) (no related file):*
@SanjayVas can you take a look at this?

___

**Review by ple13 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 5 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: all files reviewed, 5 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/cc/math/distributed_discrete_gaussian_noiser.cc` line 19 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTQqFEj6hGmHKEeTohn:-NTQqFEj6hGmHKEeToho:b-4g31r9) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/883ae515075a7073aa9f6d3c80bb9c28ed090938/src/main/cc/math/distributed_discrete_gaussian_noiser.cc#L19)):*
> ```cpp
> #include <random>
> 
> #include "src/main/cc/math/open_ssl_uniform_random_generator.h"
> ```

We have this specified as the include prefix, so you shouldn't have it in any `#include` directive.



_Code quote:_
```cpp
src/main/cc/
```
___
*[`src/main/cc/math/distributed_geometric_noiser.h` line 48 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTQsimiCrRxk7N7eXKN:-NTQsimiCrRxk7N7eXKO:b7uba8x) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/883ae515075a7073aa9f6d3c80bb9c28ed090938/src/main/cc/math/distributed_geometric_noiser.h#L48)):*
> ```objc
> 
>   [[nodiscard]] absl::StatusOr<int64_t> GetPolyaRandomVariable(
>       double r, double p, OpenSslUniformRandomGenerator rnd) const;
> ```

Should this be tied to a specific implementation? Should our Noiser impls not just accept any `UniformRandomBitGenerator` (e.g. in the constructor), and just document the properties it should satisfy for DP? Our own calling code would use `OpenSslUniformRandomGenerator` of course.



_Code quote:_
```objc
OpenSslUniformRandomGenerator
```
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTQrudb1BE_tpQNpl1X:-NTQrudb1BE_tpQNpl1Y:bf3wbrc) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/883ae515075a7073aa9f6d3c80bb9c28ed090938/src/main/cc/math/open_ssl_uniform_random_generator.h#L22)):*
> ```objc
> #include <stdexcept>
> 
> #include "openssl/rand.h"
> ```

Did you mean to put this in the source file? It doesn't appear to be referenced here in the header.



_Code quote:_
```objc
#include "openssl/rand.h"
```
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTQquO5AcRTfmq_6SgA:-NTQquO5AcRTfmq_6SgB:b8dt1j5) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/883ae515075a7073aa9f6d3c80bb9c28ed090938/src/main/cc/math/open_ssl_uniform_random_generator.h#L26)):*
> ```objc
> namespace wfa::math {
> 
> class OpenSslUniformRandomGenerator {
> ```

Ensure this satisfies [`UniformRandomBitGenerator`](https://en.cppreference.com/w/cpp/named_req/UniformRandomBitGenerator) and document that it does.
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 34 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTQr7PTCduXv6a820IA:-NTQr7PTCduXv6a820IB:bc1f6py) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/883ae515075a7073aa9f6d3c80bb9c28ed090938/src/main/cc/math/open_ssl_uniform_random_generator.h#L34)):*
> ```objc
>   using result_type = uint64_t;
> 
>   uint64_t operator()();
> ```

Use `result_type`



_Code quote:_
```objc
uint64_t
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: 1 of 7 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/cc/math/distributed_discrete_gaussian_noiser.cc` line 19 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTQqFEj6hGmHKEeTohn:-NTUkv9P-JJ4JbLpX1Cu:b-g6jf0n) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/883ae515075a7073aa9f6d3c80bb9c28ed090938/src/main/cc/math/distributed_discrete_gaussian_noiser.cc#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We have this specified as the include prefix, so you shouldn't have it in any `#include` directive.
</blockquote></details>

Done.
Thanks. I revisited all `includes` for these files.
___
*[`src/main/cc/math/distributed_geometric_noiser.h` line 48 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTQsimiCrRxk7N7eXKN:-NTUj5aX3fqTzts9yJdU:b5n5aqa) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/883ae515075a7073aa9f6d3c80bb9c28ed090938/src/main/cc/math/distributed_geometric_noiser.h#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Should this be tied to a specific implementation? Should our Noiser impls not just accept any `UniformRandomBitGenerator` (e.g. in the constructor), and just document the properties it should satisfy for DP? Our own calling code would use `OpenSslUniformRandomGenerator` of course.
</blockquote></details>

I think this will be refactored in the future that allows pass a random generator.
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTQrudb1BE_tpQNpl1X:-NTUkIrrDYh6EM6WNoEF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/883ae515075a7073aa9f6d3c80bb9c28ed090938/src/main/cc/math/open_ssl_uniform_random_generator.h#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Did you mean to put this in the source file? It doesn't appear to be referenced here in the header.
</blockquote></details>

Done.
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTQquO5AcRTfmq_6SgA:-NTUkKGi8U9rt28_RdoV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/883ae515075a7073aa9f6d3c80bb9c28ed090938/src/main/cc/math/open_ssl_uniform_random_generator.h#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ensure this satisfies [`UniformRandomBitGenerator`](https://en.cppreference.com/w/cpp/named_req/UniformRandomBitGenerator) and document that it does.
</blockquote></details>

Done.
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 34 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTQr7PTCduXv6a820IA:-NTUkL8Y-rLAEfQ11OxH:b5eknby) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/883ae515075a7073aa9f6d3c80bb9c28ed090938/src/main/cc/math/open_ssl_uniform_random_generator.h#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use `result_type`
</blockquote></details>

Done.
I wonder if I need to use `result_type` in `.cc` file as well? But seems I have to add another `using result_type = uint64_t;` there.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/cc/math/distributed_geometric_noiser.h` line 48 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTQsimiCrRxk7N7eXKN:-NTUqq8s5hS0IqOJ2z02:bwuj07l) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/883ae515075a7073aa9f6d3c80bb9c28ed090938/src/main/cc/math/distributed_geometric_noiser.h#L48)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I think this will be refactored in the future that allows pass a random generator.
</blockquote></details>

Can you add a TODO for that so we don't lose track of it?
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 34 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTQr7PTCduXv6a820IA:-NTUuu-AE_vNSqAx4YXV:b-kt0g5r) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/883ae515075a7073aa9f6d3c80bb9c28ed090938/src/main/cc/math/open_ssl_uniform_random_generator.h#L34)):*
> I wonder if I need to use result_type in .cc file as well? But seems I have to add another using result_type = uint64_t; there.

Can you not reference it as `OpenSslUniformRandomGenerator::result_type`?
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 22 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTUv8VbCyu_WFqbds6Y:-NTUv8VbCyu_WFqbds6Z:brrl5ea) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c9733d21a55480f206f8fb9d7a6c0fb76d6a80cc/src/main/cc/math/open_ssl_uniform_random_generator.h#L22)):*
> ```objc
> namespace wfa::math {
> 
> /**
> ```

Wrong syntax for C++ class comments. See https://google.github.io/styleguide/cppguide.html#Class_Comments
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 30 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTUxmZP9qnZ-e4r34sr:-NTUxmZP9qnZ-e4r34ss:b-bue6pc) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c9733d21a55480f206f8fb9d7a6c0fb76d6a80cc/src/main/cc/math/open_ssl_uniform_random_generator.cc#L30)):*
> ```cpp
>     attempts += 1;
>     if (attempts > MAX_ATTEMPTS) {
>       throw std::runtime_error("Failed to generate a random number.");
> ```

Our code must be exception-free. See https://google.github.io/styleguide/cppguide.html#Exceptions



_Code quote:_
```cpp
      throw std::runtime_error("Failed to generate a random number.");
```

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/cc/math/distributed_geometric_noiser.h` line 48 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTQsimiCrRxk7N7eXKN:-NTV5PMq39-VhQy8S79g:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/883ae515075a7073aa9f6d3c80bb9c28ed090938/src/main/cc/math/distributed_geometric_noiser.h#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can you add a TODO for that so we don't lose track of it?
</blockquote></details>

Done.
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 34 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTQr7PTCduXv6a820IA:-NTV5Sin8QEDXXstQj9B:bcidwnu) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/883ae515075a7073aa9f6d3c80bb9c28ed090938/src/main/cc/math/open_ssl_uniform_random_generator.h#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I wonder if I need to use result_type in .cc file as well? But seems I have to add another using result_type = uint64_t; there.

Can you not reference it as `OpenSslUniformRandomGenerator::result_type`?
</blockquote></details>

Sorry I didn't get it. Is it fine to keep using `uint64_t` in `.cc` file?
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 22 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTUv8VbCyu_WFqbds6Y:-NTV5QJYAxljapJKfES-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c9733d21a55480f206f8fb9d7a6c0fb76d6a80cc/src/main/cc/math/open_ssl_uniform_random_generator.h#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Wrong syntax for C++ class comments. See https://google.github.io/styleguide/cppguide.html#Class_Comments
</blockquote></details>

Done.
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 30 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTUxmZP9qnZ-e4r34sr:-NTV5CkR2JOalmZ5R327:bb1s6wc) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c9733d21a55480f206f8fb9d7a6c0fb76d6a80cc/src/main/cc/math/open_ssl_uniform_random_generator.cc#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Our code must be exception-free. See https://google.github.io/styleguide/cppguide.html#Exceptions
</blockquote></details>

Can we keep the `throw` here and rely on the caller to do `ASSIGN_OR_RETURN`?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 34 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTQr7PTCduXv6a820IA:-NTV9M_386reUyXMrbFj:biaggbn) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/883ae515075a7073aa9f6d3c80bb9c28ed090938/src/main/cc/math/open_ssl_uniform_random_generator.h#L34)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Sorry I didn't get it. Is it fine to keep using `uint64_t` in `.cc` file?
</blockquote></details>

If you must, but I think that the `.cc` file can reference this `result_type` as `OpenSslUniformRandomGenerator::result_type`. The fact that it can be referenced as `OpenSslUniformRandomGenerator::result_type` is in fact part of the UBRG requirement.
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 30 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTUxmZP9qnZ-e4r34sr:-NTV9-G36tubxlbOM9aa:b-4ri79y) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c9733d21a55480f206f8fb9d7a6c0fb76d6a80cc/src/main/cc/math/open_ssl_uniform_random_generator.cc#L30)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Can we keep the `throw` here and rely on the caller to do `ASSIGN_OR_RETURN`?
</blockquote></details>

ASSIGN_OR_RETURN is for code that uses absl::Status

Exceptions are completely forbidden in our C++ code. There are no exceptions to this rule.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 30 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTUxmZP9qnZ-e4r34sr:-NT_2bmj40YQlR4pAwKH:b-5od742) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c9733d21a55480f206f8fb9d7a6c0fb76d6a80cc/src/main/cc/math/open_ssl_uniform_random_generator.cc#L30)):*
Given this function has to return uint64_t because it will be called by std:: and absl:: functions, how does it inform the caller when it fails? Do you have any idea?

>  There are no exceptions
Nice pun.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 30 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTUxmZP9qnZ-e4r34sr:-NT_N4Tg1fZgRWHJfHB-:bxgrhzi) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c9733d21a55480f206f8fb9d7a6c0fb76d6a80cc/src/main/cc/math/open_ssl_uniform_random_generator.cc#L30)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Given this function has to return uint64_t because it will be called by std:: and absl:: functions, how does it inform the caller when it fails? Do you have any idea?

>  There are no exceptions
Nice pun.
</blockquote></details>

Don't bother with the max attempts check. absl::BitGen doesn't appear to implement such a check.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 30 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTUxmZP9qnZ-e4r34sr:-NT_dbJX7CZg5wQMpdX3:byyyvj7) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c9733d21a55480f206f8fb9d7a6c0fb76d6a80cc/src/main/cc/math/open_ssl_uniform_random_generator.cc#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't bother with the max attempts check. absl::BitGen doesn't appear to implement such a check.
</blockquote></details>

The possibility that RAND_bytes returns <= 0 is very low. Thus I keep the retry mechanism but do not throw error when it reach the attempts.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 30 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTUxmZP9qnZ-e4r34sr:-NT_fh1o9w8yAGvvPYXi:bs068c5) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c9733d21a55480f206f8fb9d7a6c0fb76d6a80cc/src/main/cc/math/open_ssl_uniform_random_generator.cc#L30)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

The possibility that RAND_bytes returns <= 0 is very low. Thus I keep the retry mechanism but do not throw error when it reach the attempts.
</blockquote></details>

This is meant to be a secure random generator, so returning any other value is a problem. In this case, it would actually be more correct to infinite loop IMO.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 30 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTUxmZP9qnZ-e4r34sr:-NT_gSkC-I9LMqRk_43e:b280zby) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c9733d21a55480f206f8fb9d7a6c0fb76d6a80cc/src/main/cc/math/open_ssl_uniform_random_generator.cc#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is meant to be a secure random generator, so returning any other value is a problem. In this case, it would actually be more correct to infinite loop IMO.
</blockquote></details>

Sounds good to me. @ple13 Could you please share some thoughts?

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.cc` line 30 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27#-NTUxmZP9qnZ-e4r34sr:-NTpRvMDDOaGPYSl5lk-:bamwub5) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/c9733d21a55480f206f8fb9d7a6c0fb76d6a80cc/src/main/cc/math/open_ssl_uniform_random_generator.cc#L30)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Sounds good to me. @ple13 Could you please share some thoughts?
</blockquote></details>

After discussion with @ple13, now the generator will check the seed status before generation. Thus no need to check the return code of RAND_bytes.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by ple13 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by ple13 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by ple13 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
