### PR TITLE
Refactor NoiserOptions to share a base class

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/21)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Review by iverson52000 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
