### PR TITLE
Add a new uniform pseudorandom generator.

### PR DESCRIPTION
**Pull request by ple13**
Given the same seed and iv, the uniform pseudorandom generator will generate the same pseudorandom sequences.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32)

**Review by renjiezh — COMMENTED** [review]
Looks good to me. I will approve once Ben gives a LGTM.

A question regarding the implementation in Java (used by EDP):
If we wrap this class in a JNI function, the input will be seed,  iv (guess we can combine them into one string) , and the size of output.
However, the JNI function is stateless so it is not supposed to be called twice to get `random_seq_1` and `random_seq_2`. Seems we have to force the user of java to only call JNI once and separate the output into multiple strings as they need? Please let me know if this is true.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-:-NjKAZVlAUXbnWb_5gm5:bh816qj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @benjaminkreuter and @SanjayVas)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32)* status: all files reviewed, 1 unresolved discussion (waiting on @benjaminkreuter, @ple13, and @SanjayVas)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 71 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-NjO4ObI3H4tBlYzezaV:-NjO4ObJ6-Lf9X2F6qLW:bbp0vld) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/a0f9ef86a0501565d19d2d2c1c9976901437f29f/src/main/cc/math/open_ssl_uniform_random_generator.h#L71)):*
> ```objc
> 
>   // Generate a vector of pseudorandom bytes with the given size.
>   absl::StatusOr<std::vector<unsigned char>> GetPseudorandomBytes(int size);
> ```

Use an unsigned int for the size?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32)* status: all files reviewed, 5 unresolved discussions (waiting on @benjaminkreuter and @ple13)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-NjOOwzX6HI0MOpUEDBc:-NjOOwzY9lIiudm1CbE6:bq4i63a) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/5f069f24e473d730a716df636efe3bafa8f5952d/src/main/cc/math/open_ssl_uniform_random_generator.h#L34)):*
> ```objc
> 
> inline constexpr int kBytesPerAES256Seed = 32;
> inline constexpr int kBytesPerAES256IV = 16;
> ```

nit: follow standard camel-casing rules w.r.t. abbreviations. This is a section from the Kotlin style guide, but it applies to camel case in all languages: https://developer.android.com/kotlin/style-guide#camel_case



_Suggestion:_
```objc
kBytesPerAes256Iv
```
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 59 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-NjOQV6Y97o0iYpHoh6B:-NjOQV6Y97o0iYpHoh6C:b8oma7l) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/5f069f24e473d730a716df636efe3bafa8f5952d/src/main/cc/math/open_ssl_uniform_random_generator.h#L59)):*
> ```objc
> };
> 
> class UniformPseudoRandomGenerator {
> ```

Split out the interface/base class from the specific OpenSSL-based impl (separate header).
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 61 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-NjOPyCDCMINvvmzeNX_:-NjOPyCDCMINvvmzeNXa:bv79r0h) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/5f069f24e473d730a716df636efe3bafa8f5952d/src/main/cc/math/open_ssl_uniform_random_generator.h#L61)):*
> ```objc
> class UniformPseudoRandomGenerator {
>  public:
>   // Create a uniform pseudorandom generator from a seed and an iv.
> ```

nit: I believe IV stands for "initialization vector", so should be upper-case in comments.



_Suggestion:_
```objc
IV
```
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-NjOQE4h04dpxx0LFoeV:-NjOQE4h04dpxx0LFoeW:b3wix5u) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/5f069f24e473d730a716df636efe3bafa8f5952d/src/main/cc/math/open_ssl_uniform_random_generator.h#L62)):*
> ```objc
>  public:
>   // Create a uniform pseudorandom generator from a seed and an iv.
>   // The seed and iv needs to have the length of 32 and 16 bytes respectively.
> ```

nit: reference the public constants for the sizes



_Code quote:_
```objc
32 and 16 bytes
```

**Review by ple13 — COMMENTED** [review]
It can be called once to get all the correlated randomness, or can be called multiple times each with a different seed.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-:-NjTnAas4vk5fdrtytcQ:b-tvimlc)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @benjaminkreuter, @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 71 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-NjO4ObI3H4tBlYzezaV:-NjTmo5x-ijf7zZmM9SN:b-llb2od) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/a0f9ef86a0501565d19d2d2c1c9976901437f29f/src/main/cc/math/open_ssl_uniform_random_generator.h#L71)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Use an unsigned int for the size?
</blockquote></details>

Fixed. Used uint64_t instead of unsigned int to support an array of size greater than 4 billions.
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-NjOOwzX6HI0MOpUEDBc:-NjTmZQX6XA-oxIYqOjm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/5f069f24e473d730a716df636efe3bafa8f5952d/src/main/cc/math/open_ssl_uniform_random_generator.h#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: follow standard camel-casing rules w.r.t. abbreviations. This is a section from the Kotlin style guide, but it applies to camel case in all languages: https://developer.android.com/kotlin/style-guide#camel_case
</blockquote></details>

Done.
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 59 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-NjOQV6Y97o0iYpHoh6B:-NjTmdFS4onwadKNm5v9:b-mmlp8h) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/5f069f24e473d730a716df636efe3bafa8f5952d/src/main/cc/math/open_ssl_uniform_random_generator.h#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Split out the interface/base class from the specific OpenSSL-based impl (separate header).
</blockquote></details>

Added a new header for the abstract class UniformPseudorandomGenerator.
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 61 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-NjOPyCDCMINvvmzeNX_:-NjTmjO12P9VNV3R-czm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/5f069f24e473d730a716df636efe3bafa8f5952d/src/main/cc/math/open_ssl_uniform_random_generator.h#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: I believe IV stands for "initialization vector", so should be upper-case in comments.
</blockquote></details>

Done.
___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-NjOQE4h04dpxx0LFoeV:-NjTmlSn1Q_uT29Jz_9E:b2gpk6e) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/5f069f24e473d730a716df636efe3bafa8f5952d/src/main/cc/math/open_ssl_uniform_random_generator.h#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: reference the public constants for the sizes
</blockquote></details>

Added references for these constants.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32)* status: all files reviewed, 2 unresolved discussions (waiting on @benjaminkreuter, @kungfucraig, and @ple13)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-NjOQE4h04dpxx0LFoeV:-Nji6YHR0PDh79rvS96z:b-nl843b) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/5f069f24e473d730a716df636efe3bafa8f5952d/src/main/cc/math/open_ssl_uniform_random_generator.h#L62)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Added references for these constants.
</blockquote></details>

I still see "32" and "16" in this documentation. I was expecting something like the following:

```
// `key` and `iv` need to have the length of `kBytesPerAes256Key` and `kBytesPerAes256Iv`, respectively.
```

**Review by kungfucraig — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32)* status: all files reviewed, 1 unresolved discussion (waiting on @benjaminkreuter and @ple13)

**Review by renjiezh — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32)* status: all files reviewed, 1 unresolved discussion (waiting on @benjaminkreuter and @ple13)

**Comment by SanjayVas** [comment]
I took the liberty of updating the PR title according to https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/dev-standards.md#pull-request-description

**Review by ple13 — COMMENTED** [review]
Thanks Sanjay!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-:-NjnNqMX7RO6oubuBA5x:bc3dx59)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @benjaminkreuter, @kungfucraig, and @SanjayVas)

___
*[`src/main/cc/math/open_ssl_uniform_random_generator.h` line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-NjOQE4h04dpxx0LFoeV:-NjnWhFB8lAujAEAe8Lg:bnnsqyj) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/5f069f24e473d730a716df636efe3bafa8f5952d/src/main/cc/math/open_ssl_uniform_random_generator.h#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I still see "32" and "16" in this documentation. I was expecting something like the following:

```
// `key` and `iv` need to have the length of `kBytesPerAes256Key` and `kBytesPerAes256Iv`, respectively.
```
</blockquote></details>

Fixed. I've updated the text.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @benjaminkreuter)

**Review by benjaminkreuter — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-:-NkROM5n281_5izEu6-q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by stevenwarejones — COMMENTED** [review]
are there plans to make a java version of this for any-sketch-java?

> Reviewed 1 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-:-NkVMzvP-SpJOjMn8BfY:b4jvmjo)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by ple13 — COMMENTED** [review]
we plan to add a JNI function in any-sketch-java that calls the c++ code.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/32#-:-NkVxd670pojRPELp6AW:b-r9in9m)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
