### PR TITLE
Verify the OpenSSL implementation of the AES counter mode against NIST's test vector.

### PR DESCRIPTION
**Pull request by ple13**
NIST provides test vectors for the AES-based block ciphers at the NIST SP 800-38A document (https://csrc.nist.gov/pubs/sp/800/38/a/final).

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/34)

**Review by renjiezh — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/34#-:-NlQ6QcA1oW-QXuyIJ5T:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @SanjayVas)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/34)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/34)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/34)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Pull request merged**
