### PR TITLE
Migrate to Bzlmod.

### PR DESCRIPTION
**Pull request by SanjayVas**
This updates Bazel to 6.4.0.

### CODE REVIEW

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/33)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`.bazelrc` line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/33#-Nl3pq8uBIvjfPDnTBIQ:-Nl4v-bm3TEQtBpWIU09:b-74ya22) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/209f173691097607a1796c7c20c055ccd6e3e727/.bazelrc#L4)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what is this for?
</blockquote></details>

This is to include the Bazel registry for our modules in addition to the Bazel Central Registry (BCR).

Sorry, I hadn't meant to send this out for review yet as it's not a leaf repo and therefore currently depends on repos under my GitHub user. I'll send out PRs later for setting up the modules and Bazel registry in the WFA org.
___
*[`build/non_module_deps.bzl` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/33#-Nl3qIPP3YeU41CRpUPC:-Nl4vls739Ivbz_Tm-2C:b-ihrcag) ([raw file](https://github.com/world-federation-of-advertisers/any-sketch/blob/209f173691097607a1796c7c20c055ccd6e3e727/build/non_module_deps.bzl#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't this be coming from common-cpp?
</blockquote></details>

No.

1. Bzlmod uses [strict dependency visibility](https://bazel.build/external/module#repository_names_and_strict_deps), you have to indicate all direct dependencies even if they are also included transitively.
2. common-cpp doesn't actually use this, so it does not have this dependency post-migration. See https://github.com/world-federation-of-advertisers/common-cpp/pull/40

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/33)* status: 4 of 7 files reviewed, 2 unresolved discussions

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/33)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/33)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/any-sketch/33)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Comment by SanjayVas** [comment]
I'm going to wait for pending PR #39 to be merged to avoid disruption.

**Pull request merged**
